--- #YAML:1.0
name:               Thread-Tie
version:            0.13
abstract:           tie variables into a thread of their own
author:
    - Elizabeth Mattijsen (liz@dijkmat.nl)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    load:               0.11
    Thread::Serialize:  0.07
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
