# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Tie
version:      0.12
version_from: lib/Thread/Tie.pm
installdirs:  site
requires:
    load:                          0.11
    Thread::Serialize:             0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
